import type { LessonModule } from "@/core/lesson"
import { lesson as d01 } from "@/lessons/01-gpu-nasil-calisir/lesson"
import { lesson as d02 } from "@/lessons/02-webgl-ve-webgpu/lesson"
import { lesson as d03 } from "@/lessons/03-webgpu-renderer/lesson"
import { lesson as d04 } from "@/lessons/04-shader-nedir/lesson"
import { lesson as d05 } from "@/lessons/05-coordinate-systems/lesson"
import { lesson as d06 } from "@/lessons/06-tsl-nedir/lesson"
import { lesson as d07 } from "@/lessons/07-tsl-veri-tipleri/lesson"
import { lesson as d08 } from "@/lessons/08-tsl-operations/lesson"
import { lesson as d09 } from "@/lessons/09-swizzling/lesson"
import { lesson as d10 } from "@/lessons/10-uniform/lesson"
import { lesson as d11 } from "@/lessons/11-variable/lesson"
import { lesson as d12 } from "@/lessons/12-fn/lesson"
import { lesson as d13 } from "@/lessons/13-uv-nedir/lesson"
import { lesson as d14 } from "@/lessons/14-uv-manipulation/lesson"
import { lesson as d15 } from "@/lessons/15-procedural-patterns/lesson"
import { lesson as d16 } from "@/lessons/16-texture-sampling/lesson"
import { lesson as d17 } from "@/lessons/17-texture-distortion/lesson"
import { lesson as d18 } from "@/lessons/18-noise-mantigi/lesson"
import { lesson as d19 } from "@/lessons/19-noise-procedural/lesson"
import { lesson as d20 } from "@/lessons/20-position-nodes/lesson"
import { lesson as d21 } from "@/lessons/21-vertex-displacement/lesson"
import { lesson as d22 } from "@/lessons/22-normal/lesson"
import { lesson as d23 } from "@/lessons/23-node-materials/lesson"
import { lesson as d24 } from "@/lessons/24-material-nodes/lesson"
import { lesson as d25 } from "@/lessons/25-fresnel/lesson"
import { lesson as d26 } from "@/lessons/26-time/lesson"
import { lesson as d27 } from "@/lessons/27-animated-noise/lesson"
import { lesson as d28 } from "@/lessons/28-coffee-smoke/lesson"
import { lesson as d29 } from "@/lessons/29-hologram-shield/lesson"
import { lesson as d30 } from "@/lessons/30-particle-sistemleri/lesson"
import { lesson as d31 } from "@/lessons/31-tsl-particles/lesson"
import { lesson as d32 } from "@/lessons/32-galaxy/lesson"
import { lesson as d33 } from "@/lessons/33-explosion/lesson"
import { lesson as d34 } from "@/lessons/34-instanced-mesh/lesson"
import { lesson as d35 } from "@/lessons/35-tsl-instances/lesson"
import { lesson as d36 } from "@/lessons/36-post-processing-mantigi/lesson"
import { lesson as d37 } from "@/lessons/37-tsl-post-processing/lesson"
import { lesson as d38 } from "@/lessons/38-bloom/lesson"
import { lesson as d39 } from "@/lessons/39-depth-buffer/lesson"
import { lesson as d40 } from "@/lessons/40-depth-effects/lesson"
import { lesson as d41 } from "@/lessons/41-compute-shader-mantigi/lesson"
import { lesson as d42 } from "@/lessons/42-webgpu-compute/lesson"
import { lesson as d43 } from "@/lessons/43-gpu-particle-simulation/lesson"
import { lesson as d44 } from "@/lessons/44-gpgpu/lesson"
import { lesson as d45 } from "@/lessons/45-particle-physics/lesson"
import { lesson as d46 } from "@/lessons/46-procedural-environment/lesson"
import { lesson as d47 } from "@/lessons/47-snow/lesson"
import { lesson as d48 } from "@/lessons/48-performance/lesson"
import { lesson as d49 } from "@/lessons/49-threejs-debug/lesson"
import { lesson as d50 } from "@/lessons/50-chrome-devtools/lesson"
import { lesson as d51 } from "@/lessons/51-webgpu-debug-araclari/lesson"
import { lesson as d52 } from "@/lessons/52-gpu-hatalari/lesson"
import { lesson as d53 } from "@/lessons/53-final-project/lesson"

export const dersler: LessonModule[] = [
	d01, d02, d03, d04, d05, d06, d07, d08, d09, d10,
	d11, d12, d13, d14, d15, d16, d17, d18, d19, d20,
	d21, d22, d23, d24, d25, d26, d27, d28, d29, d30,
	d31, d32, d33, d34, d35, d36, d37, d38, d39, d40,
	d41, d42, d43, d44, d45, d46, d47, d48, d49, d50,
	d51, d52, d53
]
